# Generated by Django 2.2.4 on 2021-08-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('photo', models.ImageField(blank=True, upload_to='Expert/', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'expert',
                'verbose_name_plural': 'experts',
            },
        ),
    ]
