# Generated by Django 2.2.4 on 2021-08-06 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsApp', '0002_mynew_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynew',
            name='collected',
            field=models.ManyToManyField(blank=True, related_name='collected_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mynew',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
